### ISSUE TITLE
[RFC] Use black formatter?

### ISSUE THREAD

**Issue by siddharth-krishna** [microsoft/times-excel-reader#6]
I propose formatting the codebase using https://pypi.org/project/black/ . It's easy to set up locally to format-on-save, and I can add it to the CI to check pushed commits/PRs. From the doc, benefits of using black:

> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
>
> Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead.
>
> Black makes code review faster by producing the smallest diffs possible.

Thoughts, @samwebster @tminka @niloyroot ?

**Comment by samwebster** [comment]
Sounds like a great idea to me. Thanks

**Comment by niloyroot** [comment]
Just checked it out, this seems very cool!

**Comment by siddharth-krishna** [comment]
Closed via #8
